# Generated by Django 5.2.6 on 2025-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='output_bot',
            field=models.CharField(max_length=10000),
        ),
    ]
