# Generated by Django 5.2.6 on 2025-09-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0002_alter_history_output_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='output_bot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_input',
            field=models.CharField(max_length=100),
        ),
    ]
