# Generated by Django 5.2.6 on 2025-09-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0003_alter_history_output_bot_alter_history_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='output_bot',
            field=models.BooleanField(default=2),
        ),
    ]
