# Generated by Django 5.2.6 on 2025-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0007_remove_book_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
