# Generated by Django 4.2.24 on 2025-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0008_chat_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='answer',
            field=models.CharField(max_length=1000000),
        ),
    ]
