# Generated by Django 4.2.24 on 2025-09-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0011_alter_chat_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
