# Generated by Django 5.2.6 on 2025-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=10000)),
                ('output_bot', models.CharField(max_length=100000)),
            ],
        ),
    ]
