# Generated by Django 5.2.6 on 2025-09-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0004_alter_history_output_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='output_bot',
            field=models.BooleanField(default=1),
        ),
    ]
