# Generated by Django 5.2.6 on 2025-09-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0005_alter_history_output_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500, null=True)),
                ('Author', models.CharField(max_length=100, null=True)),
                ('ISBN', models.CharField(max_length=1000)),
                ('Category', models.CharField(max_length=60, null=True)),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
