# Generated by Django 5.2.6 on 2025-09-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphdisplay', '0006_book_delete_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Quantity',
        ),
    ]
